Algoritmo "semnome"
// Disciplina   : PA
// Professor   : cintia pinho
// Descrição   :converter em dolar
// Autor(a)    :isadora duarte
// Data atual  : 21/06/2021
Var
cotacao,valor,resultado:real
Inicio
escreval("escreva o valor da cotacao do dolar")
leia(cotacao)
escreval("o quanto quer converter: ")
leia(valor)
//execução
resultado <- valor/cotacao
//saida
escreval(valor."reais.e o mesmo que." resultado, dolares")
Fimalgoritmo